CREATE TABLE `sms`.`T_ACOUNT_RECORD`  ( 
`ID` INT(20) NOT NULL AUTO_INCREMENT, 
`CLIENTID` INT(20), 
`CORPNAME` VARCHAR(256), 
`PAIDVALUE` INT(0), 
`CREATETIME` DATETIME, 
PRIMARY KEY (`ID`) 
);

CREATE TABLE `sms`.`T_ADMIN_USER`  ( 
`ID` INT(0) NOT NULL AUTO_INCREMENT, 
`PASSWORD` VARCHAR(256), 
`USERCODE` VARCHAR(256), 
`EMAIL` VARCHAR(256), 
`REAL_NAME` VARCHAR(256), 
`STATUS` SMALLINT, 
`CLIENTID` INT(0), 
PRIMARY KEY (`ID`) 
);

CREATE TABLE `sms`.`T_BLACK_LIST`  ( 
`ID` INT(20) NOT NULL AUTO_INCREMENT, 
`MOBILE` VARCHAR(256), 
PRIMARY KEY (`ID`) 
);

CREATE TABLE `sms`.`T_CHANNEL`  ( 
`ID` INT(20) NOT NULL AUTO_INCREMENT, 
`CHANNELNAME` VARCHAR(256), 
`CHANNELTYPE` TINYINT, 
`SPNUMBER` VARCHAR(256), 
`PROTOCALTYPE` TINYINT, 
PRIMARY KEY (`ID`) 
);

CREATE TABLE `sms`.`T_CLIENT_BUSINESS`  ( 
`ID` INT(20) NOT NULL AUTO_INCREMENT, 
`CORPNAME` VARCHAR(256), 
`USERCODE` VARCHAR(256), 
`PWD` VARCHAR(256), 
`IPADDRESS` VARCHAR(256), 
`ISRETURNSTATUS` TINYINT, 
`RECEIVESTATUSURL` VARCHAR(256), 
`PRIORITY` TINYINT, 
`USERTYPE` TINYINT, 
`STATE` INT(0), 
`MOBILE` VARCHAR(256), 
`PAID_VALUE_STR` VARCHAR(256), 
PRIMARY KEY (`ID`) 
);

CREATE TABLE `sms`.`T_CLIENT_CHANNEL`  ( 
`ID` INT(20) NOT NULL AUTO_INCREMENT, 
`CLIENTID` INT(20), 
`CORPNAME` VARCHAR(256), 
`EXTENDNUMBER` VARCHAR(256), 
`PRICE` INT(0), 
`CHANNELID` INT(0), 
`CHANNELNAME` VARCHAR(256), 
PRIMARY KEY (`ID`) 
);

CREATE TABLE `sms`.`T_DIRTYWORD`  ( 
`ID` INT(20) NOT NULL AUTO_INCREMENT, 
`DIRTYWORD` VARCHAR(256), 
PRIMARY KEY (`ID`) 
);

CREATE TABLE `sms`.`T_INST`  ( 
`ID` INT(20) NOT NULL AUTO_INCREMENT, 
`INSTID` VARCHAR(256), 
`AREANAME` VARCHAR(256), 
`PARENTID` INT(20), 
`REGION` VARCHAR(256), 
`LEVEL` VARCHAR(256), 
PRIMARY KEY (`ID`) 
);

CREATE TABLE `sms`.`T_MENU`  ( 
`ID` INT(0) NOT NULL AUTO_INCREMENT, 
`NAME` VARCHAR(256), 
`PARENT_ID` INT(0), 
`URL` VARCHAR(256), 
`ICON` VARCHAR(256), 
`PERMS` VARCHAR(256), 
`TYPE` SMALLINT, 
`SORT` INT(0), 
PRIMARY KEY (`ID`) 
);

CREATE TABLE `sms`.`T_PHASE`  ( 
`ID` INT(20) NOT NULL AUTO_INCREMENT, 
`PHASE` VARCHAR(256), 
`PROV_ID` INT(20), 
`PROV_NAME` VARCHAR(256), 
`CITY_ID` INT(20), 
`CITY_NAME` VARCHAR(256), 
PRIMARY KEY (`ID`) 
);

CREATE TABLE `sms`.`T_ROLE`  ( 
`ID` INT(0) NOT NULL AUTO_INCREMENT, 
`NAME` VARCHAR(256), 
`REMARK` VARCHAR(256), 
`STATUS` INT(0), 
PRIMARY KEY (`ID`) 
);

CREATE TABLE `sms`.`T_ROLE_MENU_KEY`  ( 
`ROLE_ID` INT(0), 
`MENU_ID` INT(0)
);

CREATE TABLE `sms`.`T_USER_ROLE_KEY`  ( 
`USER_ID` INT(0), 
`ROLE_ID` INT(0)
);

