package com.customized.libs.shardingsphere.dao.generate;

import com.customized.libs.shardingsphere.entity.generate.TRouteChannel;
import com.customized.libs.shardingsphere.entity.generate.TRouteChannelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TRouteChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_channel
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    int countByExample(TRouteChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_channel
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    int deleteByExample(TRouteChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_channel
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_channel
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    int insert(TRouteChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_channel
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    int insertSelective(TRouteChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_channel
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    List<TRouteChannel> selectByExample(TRouteChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_channel
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    TRouteChannel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_channel
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") TRouteChannel record, @Param("example") TRouteChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_channel
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    int updateByExample(@Param("record") TRouteChannel record, @Param("example") TRouteChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_channel
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    int updateByPrimaryKeySelective(TRouteChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_channel
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    int updateByPrimaryKey(TRouteChannel record);
}