test:
  password: 0654321
# 配置eureka获取服务地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
  # 配置Swagger相关信息
  instance:
    prefer-ip-address: true
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html
  # ${server.port}为该服务的端口号
spring:
  ###ThymeLeaf配置
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML5
    #编码 可不用配置
    encoding: UTF-8
    #内容类别,可不用配置
    #开发配置为false,避免修改模板还要重启服务器
    cache: true
    servlet:
      content-type: text/html
  resources:
    add-mappings: true
  application:
    name: eureka-server
  data:
    mongodb:
      oss-uri: mongodb://172.19.100.96:27017/privateupload
server:
  port: 8080
logging:
  file: logs/springboot.log
  level:
    ROOT: debug
