package com.customized.libs.shardingsphere.entity.generate;

import java.io.Serializable;

public class TRouteChannel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_route_channel.ID
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_route_channel.NAME
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_route_channel.CHANNEL
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_route_channel.PAY_CHANNEL
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    private Integer payChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_route_channel.TRADE_AMOUNT_LIMIT_DAILY
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    private Long tradeAmountLimitDaily;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_route_channel.TRADE_PER_AMOUNT_MIN_LIMIT
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    private Long tradePerAmountMinLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_route_channel.TRADE_PER_AMOUNT_LIMIT
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    private Long tradePerAmountLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_route_channel.TRADE_AMOUNT_TOTAL
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    private Long tradeAmountTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_route_channel.TRADE_AMOUNT_DAILY
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    private Long tradeAmountDaily;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_route_channel.TRADE_COUNT_TOTAL
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    private Long tradeCountTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_route_channel.TRADE_COUNT_DAILY
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    private Long tradeCountDaily;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_route_channel.TRADE_START_TIME
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    private String tradeStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_route_channel.TRADE_END_TIME
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    private String tradeEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_route_channel.PRIORITY
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_route_channel
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_route_channel.ID
     *
     * @return the value of t_route_channel.ID
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_route_channel.ID
     *
     * @param id the value for t_route_channel.ID
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_route_channel.NAME
     *
     * @return the value of t_route_channel.NAME
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_route_channel.NAME
     *
     * @param name the value for t_route_channel.NAME
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_route_channel.CHANNEL
     *
     * @return the value of t_route_channel.CHANNEL
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_route_channel.CHANNEL
     *
     * @param channel the value for t_route_channel.CHANNEL
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public void setChannel(String channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_route_channel.PAY_CHANNEL
     *
     * @return the value of t_route_channel.PAY_CHANNEL
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public Integer getPayChannel() {
        return payChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_route_channel.PAY_CHANNEL
     *
     * @param payChannel the value for t_route_channel.PAY_CHANNEL
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public void setPayChannel(Integer payChannel) {
        this.payChannel = payChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_route_channel.TRADE_AMOUNT_LIMIT_DAILY
     *
     * @return the value of t_route_channel.TRADE_AMOUNT_LIMIT_DAILY
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public Long getTradeAmountLimitDaily() {
        return tradeAmountLimitDaily;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_route_channel.TRADE_AMOUNT_LIMIT_DAILY
     *
     * @param tradeAmountLimitDaily the value for t_route_channel.TRADE_AMOUNT_LIMIT_DAILY
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public void setTradeAmountLimitDaily(Long tradeAmountLimitDaily) {
        this.tradeAmountLimitDaily = tradeAmountLimitDaily;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_route_channel.TRADE_PER_AMOUNT_MIN_LIMIT
     *
     * @return the value of t_route_channel.TRADE_PER_AMOUNT_MIN_LIMIT
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public Long getTradePerAmountMinLimit() {
        return tradePerAmountMinLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_route_channel.TRADE_PER_AMOUNT_MIN_LIMIT
     *
     * @param tradePerAmountMinLimit the value for t_route_channel.TRADE_PER_AMOUNT_MIN_LIMIT
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public void setTradePerAmountMinLimit(Long tradePerAmountMinLimit) {
        this.tradePerAmountMinLimit = tradePerAmountMinLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_route_channel.TRADE_PER_AMOUNT_LIMIT
     *
     * @return the value of t_route_channel.TRADE_PER_AMOUNT_LIMIT
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public Long getTradePerAmountLimit() {
        return tradePerAmountLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_route_channel.TRADE_PER_AMOUNT_LIMIT
     *
     * @param tradePerAmountLimit the value for t_route_channel.TRADE_PER_AMOUNT_LIMIT
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public void setTradePerAmountLimit(Long tradePerAmountLimit) {
        this.tradePerAmountLimit = tradePerAmountLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_route_channel.TRADE_AMOUNT_TOTAL
     *
     * @return the value of t_route_channel.TRADE_AMOUNT_TOTAL
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public Long getTradeAmountTotal() {
        return tradeAmountTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_route_channel.TRADE_AMOUNT_TOTAL
     *
     * @param tradeAmountTotal the value for t_route_channel.TRADE_AMOUNT_TOTAL
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public void setTradeAmountTotal(Long tradeAmountTotal) {
        this.tradeAmountTotal = tradeAmountTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_route_channel.TRADE_AMOUNT_DAILY
     *
     * @return the value of t_route_channel.TRADE_AMOUNT_DAILY
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public Long getTradeAmountDaily() {
        return tradeAmountDaily;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_route_channel.TRADE_AMOUNT_DAILY
     *
     * @param tradeAmountDaily the value for t_route_channel.TRADE_AMOUNT_DAILY
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public void setTradeAmountDaily(Long tradeAmountDaily) {
        this.tradeAmountDaily = tradeAmountDaily;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_route_channel.TRADE_COUNT_TOTAL
     *
     * @return the value of t_route_channel.TRADE_COUNT_TOTAL
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public Long getTradeCountTotal() {
        return tradeCountTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_route_channel.TRADE_COUNT_TOTAL
     *
     * @param tradeCountTotal the value for t_route_channel.TRADE_COUNT_TOTAL
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public void setTradeCountTotal(Long tradeCountTotal) {
        this.tradeCountTotal = tradeCountTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_route_channel.TRADE_COUNT_DAILY
     *
     * @return the value of t_route_channel.TRADE_COUNT_DAILY
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public Long getTradeCountDaily() {
        return tradeCountDaily;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_route_channel.TRADE_COUNT_DAILY
     *
     * @param tradeCountDaily the value for t_route_channel.TRADE_COUNT_DAILY
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public void setTradeCountDaily(Long tradeCountDaily) {
        this.tradeCountDaily = tradeCountDaily;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_route_channel.TRADE_START_TIME
     *
     * @return the value of t_route_channel.TRADE_START_TIME
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public String getTradeStartTime() {
        return tradeStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_route_channel.TRADE_START_TIME
     *
     * @param tradeStartTime the value for t_route_channel.TRADE_START_TIME
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public void setTradeStartTime(String tradeStartTime) {
        this.tradeStartTime = tradeStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_route_channel.TRADE_END_TIME
     *
     * @return the value of t_route_channel.TRADE_END_TIME
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public String getTradeEndTime() {
        return tradeEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_route_channel.TRADE_END_TIME
     *
     * @param tradeEndTime the value for t_route_channel.TRADE_END_TIME
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public void setTradeEndTime(String tradeEndTime) {
        this.tradeEndTime = tradeEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_route_channel.PRIORITY
     *
     * @return the value of t_route_channel.PRIORITY
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_route_channel.PRIORITY
     *
     * @param priority the value for t_route_channel.PRIORITY
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }
}