package com.customized.libs.shardingsphere.entity.generate;

import java.util.ArrayList;
import java.util.List;

public class TRouteChannelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_route_channel
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_route_channel
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_route_channel
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_channel
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public TRouteChannelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_channel
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_channel
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_channel
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_channel
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_channel
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_channel
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_channel
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_channel
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_channel
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_route_channel
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_route_channel
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andChannelIsNull() {
            addCriterion("CHANNEL is null");
            return (Criteria) this;
        }

        public Criteria andChannelIsNotNull() {
            addCriterion("CHANNEL is not null");
            return (Criteria) this;
        }

        public Criteria andChannelEqualTo(String value) {
            addCriterion("CHANNEL =", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotEqualTo(String value) {
            addCriterion("CHANNEL <>", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThan(String value) {
            addCriterion("CHANNEL >", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThanOrEqualTo(String value) {
            addCriterion("CHANNEL >=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThan(String value) {
            addCriterion("CHANNEL <", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThanOrEqualTo(String value) {
            addCriterion("CHANNEL <=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLike(String value) {
            addCriterion("CHANNEL like", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotLike(String value) {
            addCriterion("CHANNEL not like", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelIn(List<String> values) {
            addCriterion("CHANNEL in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotIn(List<String> values) {
            addCriterion("CHANNEL not in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelBetween(String value1, String value2) {
            addCriterion("CHANNEL between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotBetween(String value1, String value2) {
            addCriterion("CHANNEL not between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andPayChannelIsNull() {
            addCriterion("PAY_CHANNEL is null");
            return (Criteria) this;
        }

        public Criteria andPayChannelIsNotNull() {
            addCriterion("PAY_CHANNEL is not null");
            return (Criteria) this;
        }

        public Criteria andPayChannelEqualTo(Integer value) {
            addCriterion("PAY_CHANNEL =", value, "payChannel");
            return (Criteria) this;
        }

        public Criteria andPayChannelNotEqualTo(Integer value) {
            addCriterion("PAY_CHANNEL <>", value, "payChannel");
            return (Criteria) this;
        }

        public Criteria andPayChannelGreaterThan(Integer value) {
            addCriterion("PAY_CHANNEL >", value, "payChannel");
            return (Criteria) this;
        }

        public Criteria andPayChannelGreaterThanOrEqualTo(Integer value) {
            addCriterion("PAY_CHANNEL >=", value, "payChannel");
            return (Criteria) this;
        }

        public Criteria andPayChannelLessThan(Integer value) {
            addCriterion("PAY_CHANNEL <", value, "payChannel");
            return (Criteria) this;
        }

        public Criteria andPayChannelLessThanOrEqualTo(Integer value) {
            addCriterion("PAY_CHANNEL <=", value, "payChannel");
            return (Criteria) this;
        }

        public Criteria andPayChannelIn(List<Integer> values) {
            addCriterion("PAY_CHANNEL in", values, "payChannel");
            return (Criteria) this;
        }

        public Criteria andPayChannelNotIn(List<Integer> values) {
            addCriterion("PAY_CHANNEL not in", values, "payChannel");
            return (Criteria) this;
        }

        public Criteria andPayChannelBetween(Integer value1, Integer value2) {
            addCriterion("PAY_CHANNEL between", value1, value2, "payChannel");
            return (Criteria) this;
        }

        public Criteria andPayChannelNotBetween(Integer value1, Integer value2) {
            addCriterion("PAY_CHANNEL not between", value1, value2, "payChannel");
            return (Criteria) this;
        }

        public Criteria andTradeAmountLimitDailyIsNull() {
            addCriterion("TRADE_AMOUNT_LIMIT_DAILY is null");
            return (Criteria) this;
        }

        public Criteria andTradeAmountLimitDailyIsNotNull() {
            addCriterion("TRADE_AMOUNT_LIMIT_DAILY is not null");
            return (Criteria) this;
        }

        public Criteria andTradeAmountLimitDailyEqualTo(Long value) {
            addCriterion("TRADE_AMOUNT_LIMIT_DAILY =", value, "tradeAmountLimitDaily");
            return (Criteria) this;
        }

        public Criteria andTradeAmountLimitDailyNotEqualTo(Long value) {
            addCriterion("TRADE_AMOUNT_LIMIT_DAILY <>", value, "tradeAmountLimitDaily");
            return (Criteria) this;
        }

        public Criteria andTradeAmountLimitDailyGreaterThan(Long value) {
            addCriterion("TRADE_AMOUNT_LIMIT_DAILY >", value, "tradeAmountLimitDaily");
            return (Criteria) this;
        }

        public Criteria andTradeAmountLimitDailyGreaterThanOrEqualTo(Long value) {
            addCriterion("TRADE_AMOUNT_LIMIT_DAILY >=", value, "tradeAmountLimitDaily");
            return (Criteria) this;
        }

        public Criteria andTradeAmountLimitDailyLessThan(Long value) {
            addCriterion("TRADE_AMOUNT_LIMIT_DAILY <", value, "tradeAmountLimitDaily");
            return (Criteria) this;
        }

        public Criteria andTradeAmountLimitDailyLessThanOrEqualTo(Long value) {
            addCriterion("TRADE_AMOUNT_LIMIT_DAILY <=", value, "tradeAmountLimitDaily");
            return (Criteria) this;
        }

        public Criteria andTradeAmountLimitDailyIn(List<Long> values) {
            addCriterion("TRADE_AMOUNT_LIMIT_DAILY in", values, "tradeAmountLimitDaily");
            return (Criteria) this;
        }

        public Criteria andTradeAmountLimitDailyNotIn(List<Long> values) {
            addCriterion("TRADE_AMOUNT_LIMIT_DAILY not in", values, "tradeAmountLimitDaily");
            return (Criteria) this;
        }

        public Criteria andTradeAmountLimitDailyBetween(Long value1, Long value2) {
            addCriterion("TRADE_AMOUNT_LIMIT_DAILY between", value1, value2, "tradeAmountLimitDaily");
            return (Criteria) this;
        }

        public Criteria andTradeAmountLimitDailyNotBetween(Long value1, Long value2) {
            addCriterion("TRADE_AMOUNT_LIMIT_DAILY not between", value1, value2, "tradeAmountLimitDaily");
            return (Criteria) this;
        }

        public Criteria andTradePerAmountMinLimitIsNull() {
            addCriterion("TRADE_PER_AMOUNT_MIN_LIMIT is null");
            return (Criteria) this;
        }

        public Criteria andTradePerAmountMinLimitIsNotNull() {
            addCriterion("TRADE_PER_AMOUNT_MIN_LIMIT is not null");
            return (Criteria) this;
        }

        public Criteria andTradePerAmountMinLimitEqualTo(Long value) {
            addCriterion("TRADE_PER_AMOUNT_MIN_LIMIT =", value, "tradePerAmountMinLimit");
            return (Criteria) this;
        }

        public Criteria andTradePerAmountMinLimitNotEqualTo(Long value) {
            addCriterion("TRADE_PER_AMOUNT_MIN_LIMIT <>", value, "tradePerAmountMinLimit");
            return (Criteria) this;
        }

        public Criteria andTradePerAmountMinLimitGreaterThan(Long value) {
            addCriterion("TRADE_PER_AMOUNT_MIN_LIMIT >", value, "tradePerAmountMinLimit");
            return (Criteria) this;
        }

        public Criteria andTradePerAmountMinLimitGreaterThanOrEqualTo(Long value) {
            addCriterion("TRADE_PER_AMOUNT_MIN_LIMIT >=", value, "tradePerAmountMinLimit");
            return (Criteria) this;
        }

        public Criteria andTradePerAmountMinLimitLessThan(Long value) {
            addCriterion("TRADE_PER_AMOUNT_MIN_LIMIT <", value, "tradePerAmountMinLimit");
            return (Criteria) this;
        }

        public Criteria andTradePerAmountMinLimitLessThanOrEqualTo(Long value) {
            addCriterion("TRADE_PER_AMOUNT_MIN_LIMIT <=", value, "tradePerAmountMinLimit");
            return (Criteria) this;
        }

        public Criteria andTradePerAmountMinLimitIn(List<Long> values) {
            addCriterion("TRADE_PER_AMOUNT_MIN_LIMIT in", values, "tradePerAmountMinLimit");
            return (Criteria) this;
        }

        public Criteria andTradePerAmountMinLimitNotIn(List<Long> values) {
            addCriterion("TRADE_PER_AMOUNT_MIN_LIMIT not in", values, "tradePerAmountMinLimit");
            return (Criteria) this;
        }

        public Criteria andTradePerAmountMinLimitBetween(Long value1, Long value2) {
            addCriterion("TRADE_PER_AMOUNT_MIN_LIMIT between", value1, value2, "tradePerAmountMinLimit");
            return (Criteria) this;
        }

        public Criteria andTradePerAmountMinLimitNotBetween(Long value1, Long value2) {
            addCriterion("TRADE_PER_AMOUNT_MIN_LIMIT not between", value1, value2, "tradePerAmountMinLimit");
            return (Criteria) this;
        }

        public Criteria andTradePerAmountLimitIsNull() {
            addCriterion("TRADE_PER_AMOUNT_LIMIT is null");
            return (Criteria) this;
        }

        public Criteria andTradePerAmountLimitIsNotNull() {
            addCriterion("TRADE_PER_AMOUNT_LIMIT is not null");
            return (Criteria) this;
        }

        public Criteria andTradePerAmountLimitEqualTo(Long value) {
            addCriterion("TRADE_PER_AMOUNT_LIMIT =", value, "tradePerAmountLimit");
            return (Criteria) this;
        }

        public Criteria andTradePerAmountLimitNotEqualTo(Long value) {
            addCriterion("TRADE_PER_AMOUNT_LIMIT <>", value, "tradePerAmountLimit");
            return (Criteria) this;
        }

        public Criteria andTradePerAmountLimitGreaterThan(Long value) {
            addCriterion("TRADE_PER_AMOUNT_LIMIT >", value, "tradePerAmountLimit");
            return (Criteria) this;
        }

        public Criteria andTradePerAmountLimitGreaterThanOrEqualTo(Long value) {
            addCriterion("TRADE_PER_AMOUNT_LIMIT >=", value, "tradePerAmountLimit");
            return (Criteria) this;
        }

        public Criteria andTradePerAmountLimitLessThan(Long value) {
            addCriterion("TRADE_PER_AMOUNT_LIMIT <", value, "tradePerAmountLimit");
            return (Criteria) this;
        }

        public Criteria andTradePerAmountLimitLessThanOrEqualTo(Long value) {
            addCriterion("TRADE_PER_AMOUNT_LIMIT <=", value, "tradePerAmountLimit");
            return (Criteria) this;
        }

        public Criteria andTradePerAmountLimitIn(List<Long> values) {
            addCriterion("TRADE_PER_AMOUNT_LIMIT in", values, "tradePerAmountLimit");
            return (Criteria) this;
        }

        public Criteria andTradePerAmountLimitNotIn(List<Long> values) {
            addCriterion("TRADE_PER_AMOUNT_LIMIT not in", values, "tradePerAmountLimit");
            return (Criteria) this;
        }

        public Criteria andTradePerAmountLimitBetween(Long value1, Long value2) {
            addCriterion("TRADE_PER_AMOUNT_LIMIT between", value1, value2, "tradePerAmountLimit");
            return (Criteria) this;
        }

        public Criteria andTradePerAmountLimitNotBetween(Long value1, Long value2) {
            addCriterion("TRADE_PER_AMOUNT_LIMIT not between", value1, value2, "tradePerAmountLimit");
            return (Criteria) this;
        }

        public Criteria andTradeAmountTotalIsNull() {
            addCriterion("TRADE_AMOUNT_TOTAL is null");
            return (Criteria) this;
        }

        public Criteria andTradeAmountTotalIsNotNull() {
            addCriterion("TRADE_AMOUNT_TOTAL is not null");
            return (Criteria) this;
        }

        public Criteria andTradeAmountTotalEqualTo(Long value) {
            addCriterion("TRADE_AMOUNT_TOTAL =", value, "tradeAmountTotal");
            return (Criteria) this;
        }

        public Criteria andTradeAmountTotalNotEqualTo(Long value) {
            addCriterion("TRADE_AMOUNT_TOTAL <>", value, "tradeAmountTotal");
            return (Criteria) this;
        }

        public Criteria andTradeAmountTotalGreaterThan(Long value) {
            addCriterion("TRADE_AMOUNT_TOTAL >", value, "tradeAmountTotal");
            return (Criteria) this;
        }

        public Criteria andTradeAmountTotalGreaterThanOrEqualTo(Long value) {
            addCriterion("TRADE_AMOUNT_TOTAL >=", value, "tradeAmountTotal");
            return (Criteria) this;
        }

        public Criteria andTradeAmountTotalLessThan(Long value) {
            addCriterion("TRADE_AMOUNT_TOTAL <", value, "tradeAmountTotal");
            return (Criteria) this;
        }

        public Criteria andTradeAmountTotalLessThanOrEqualTo(Long value) {
            addCriterion("TRADE_AMOUNT_TOTAL <=", value, "tradeAmountTotal");
            return (Criteria) this;
        }

        public Criteria andTradeAmountTotalIn(List<Long> values) {
            addCriterion("TRADE_AMOUNT_TOTAL in", values, "tradeAmountTotal");
            return (Criteria) this;
        }

        public Criteria andTradeAmountTotalNotIn(List<Long> values) {
            addCriterion("TRADE_AMOUNT_TOTAL not in", values, "tradeAmountTotal");
            return (Criteria) this;
        }

        public Criteria andTradeAmountTotalBetween(Long value1, Long value2) {
            addCriterion("TRADE_AMOUNT_TOTAL between", value1, value2, "tradeAmountTotal");
            return (Criteria) this;
        }

        public Criteria andTradeAmountTotalNotBetween(Long value1, Long value2) {
            addCriterion("TRADE_AMOUNT_TOTAL not between", value1, value2, "tradeAmountTotal");
            return (Criteria) this;
        }

        public Criteria andTradeAmountDailyIsNull() {
            addCriterion("TRADE_AMOUNT_DAILY is null");
            return (Criteria) this;
        }

        public Criteria andTradeAmountDailyIsNotNull() {
            addCriterion("TRADE_AMOUNT_DAILY is not null");
            return (Criteria) this;
        }

        public Criteria andTradeAmountDailyEqualTo(Long value) {
            addCriterion("TRADE_AMOUNT_DAILY =", value, "tradeAmountDaily");
            return (Criteria) this;
        }

        public Criteria andTradeAmountDailyNotEqualTo(Long value) {
            addCriterion("TRADE_AMOUNT_DAILY <>", value, "tradeAmountDaily");
            return (Criteria) this;
        }

        public Criteria andTradeAmountDailyGreaterThan(Long value) {
            addCriterion("TRADE_AMOUNT_DAILY >", value, "tradeAmountDaily");
            return (Criteria) this;
        }

        public Criteria andTradeAmountDailyGreaterThanOrEqualTo(Long value) {
            addCriterion("TRADE_AMOUNT_DAILY >=", value, "tradeAmountDaily");
            return (Criteria) this;
        }

        public Criteria andTradeAmountDailyLessThan(Long value) {
            addCriterion("TRADE_AMOUNT_DAILY <", value, "tradeAmountDaily");
            return (Criteria) this;
        }

        public Criteria andTradeAmountDailyLessThanOrEqualTo(Long value) {
            addCriterion("TRADE_AMOUNT_DAILY <=", value, "tradeAmountDaily");
            return (Criteria) this;
        }

        public Criteria andTradeAmountDailyIn(List<Long> values) {
            addCriterion("TRADE_AMOUNT_DAILY in", values, "tradeAmountDaily");
            return (Criteria) this;
        }

        public Criteria andTradeAmountDailyNotIn(List<Long> values) {
            addCriterion("TRADE_AMOUNT_DAILY not in", values, "tradeAmountDaily");
            return (Criteria) this;
        }

        public Criteria andTradeAmountDailyBetween(Long value1, Long value2) {
            addCriterion("TRADE_AMOUNT_DAILY between", value1, value2, "tradeAmountDaily");
            return (Criteria) this;
        }

        public Criteria andTradeAmountDailyNotBetween(Long value1, Long value2) {
            addCriterion("TRADE_AMOUNT_DAILY not between", value1, value2, "tradeAmountDaily");
            return (Criteria) this;
        }

        public Criteria andTradeCountTotalIsNull() {
            addCriterion("TRADE_COUNT_TOTAL is null");
            return (Criteria) this;
        }

        public Criteria andTradeCountTotalIsNotNull() {
            addCriterion("TRADE_COUNT_TOTAL is not null");
            return (Criteria) this;
        }

        public Criteria andTradeCountTotalEqualTo(Long value) {
            addCriterion("TRADE_COUNT_TOTAL =", value, "tradeCountTotal");
            return (Criteria) this;
        }

        public Criteria andTradeCountTotalNotEqualTo(Long value) {
            addCriterion("TRADE_COUNT_TOTAL <>", value, "tradeCountTotal");
            return (Criteria) this;
        }

        public Criteria andTradeCountTotalGreaterThan(Long value) {
            addCriterion("TRADE_COUNT_TOTAL >", value, "tradeCountTotal");
            return (Criteria) this;
        }

        public Criteria andTradeCountTotalGreaterThanOrEqualTo(Long value) {
            addCriterion("TRADE_COUNT_TOTAL >=", value, "tradeCountTotal");
            return (Criteria) this;
        }

        public Criteria andTradeCountTotalLessThan(Long value) {
            addCriterion("TRADE_COUNT_TOTAL <", value, "tradeCountTotal");
            return (Criteria) this;
        }

        public Criteria andTradeCountTotalLessThanOrEqualTo(Long value) {
            addCriterion("TRADE_COUNT_TOTAL <=", value, "tradeCountTotal");
            return (Criteria) this;
        }

        public Criteria andTradeCountTotalIn(List<Long> values) {
            addCriterion("TRADE_COUNT_TOTAL in", values, "tradeCountTotal");
            return (Criteria) this;
        }

        public Criteria andTradeCountTotalNotIn(List<Long> values) {
            addCriterion("TRADE_COUNT_TOTAL not in", values, "tradeCountTotal");
            return (Criteria) this;
        }

        public Criteria andTradeCountTotalBetween(Long value1, Long value2) {
            addCriterion("TRADE_COUNT_TOTAL between", value1, value2, "tradeCountTotal");
            return (Criteria) this;
        }

        public Criteria andTradeCountTotalNotBetween(Long value1, Long value2) {
            addCriterion("TRADE_COUNT_TOTAL not between", value1, value2, "tradeCountTotal");
            return (Criteria) this;
        }

        public Criteria andTradeCountDailyIsNull() {
            addCriterion("TRADE_COUNT_DAILY is null");
            return (Criteria) this;
        }

        public Criteria andTradeCountDailyIsNotNull() {
            addCriterion("TRADE_COUNT_DAILY is not null");
            return (Criteria) this;
        }

        public Criteria andTradeCountDailyEqualTo(Long value) {
            addCriterion("TRADE_COUNT_DAILY =", value, "tradeCountDaily");
            return (Criteria) this;
        }

        public Criteria andTradeCountDailyNotEqualTo(Long value) {
            addCriterion("TRADE_COUNT_DAILY <>", value, "tradeCountDaily");
            return (Criteria) this;
        }

        public Criteria andTradeCountDailyGreaterThan(Long value) {
            addCriterion("TRADE_COUNT_DAILY >", value, "tradeCountDaily");
            return (Criteria) this;
        }

        public Criteria andTradeCountDailyGreaterThanOrEqualTo(Long value) {
            addCriterion("TRADE_COUNT_DAILY >=", value, "tradeCountDaily");
            return (Criteria) this;
        }

        public Criteria andTradeCountDailyLessThan(Long value) {
            addCriterion("TRADE_COUNT_DAILY <", value, "tradeCountDaily");
            return (Criteria) this;
        }

        public Criteria andTradeCountDailyLessThanOrEqualTo(Long value) {
            addCriterion("TRADE_COUNT_DAILY <=", value, "tradeCountDaily");
            return (Criteria) this;
        }

        public Criteria andTradeCountDailyIn(List<Long> values) {
            addCriterion("TRADE_COUNT_DAILY in", values, "tradeCountDaily");
            return (Criteria) this;
        }

        public Criteria andTradeCountDailyNotIn(List<Long> values) {
            addCriterion("TRADE_COUNT_DAILY not in", values, "tradeCountDaily");
            return (Criteria) this;
        }

        public Criteria andTradeCountDailyBetween(Long value1, Long value2) {
            addCriterion("TRADE_COUNT_DAILY between", value1, value2, "tradeCountDaily");
            return (Criteria) this;
        }

        public Criteria andTradeCountDailyNotBetween(Long value1, Long value2) {
            addCriterion("TRADE_COUNT_DAILY not between", value1, value2, "tradeCountDaily");
            return (Criteria) this;
        }

        public Criteria andTradeStartTimeIsNull() {
            addCriterion("TRADE_START_TIME is null");
            return (Criteria) this;
        }

        public Criteria andTradeStartTimeIsNotNull() {
            addCriterion("TRADE_START_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andTradeStartTimeEqualTo(String value) {
            addCriterion("TRADE_START_TIME =", value, "tradeStartTime");
            return (Criteria) this;
        }

        public Criteria andTradeStartTimeNotEqualTo(String value) {
            addCriterion("TRADE_START_TIME <>", value, "tradeStartTime");
            return (Criteria) this;
        }

        public Criteria andTradeStartTimeGreaterThan(String value) {
            addCriterion("TRADE_START_TIME >", value, "tradeStartTime");
            return (Criteria) this;
        }

        public Criteria andTradeStartTimeGreaterThanOrEqualTo(String value) {
            addCriterion("TRADE_START_TIME >=", value, "tradeStartTime");
            return (Criteria) this;
        }

        public Criteria andTradeStartTimeLessThan(String value) {
            addCriterion("TRADE_START_TIME <", value, "tradeStartTime");
            return (Criteria) this;
        }

        public Criteria andTradeStartTimeLessThanOrEqualTo(String value) {
            addCriterion("TRADE_START_TIME <=", value, "tradeStartTime");
            return (Criteria) this;
        }

        public Criteria andTradeStartTimeLike(String value) {
            addCriterion("TRADE_START_TIME like", value, "tradeStartTime");
            return (Criteria) this;
        }

        public Criteria andTradeStartTimeNotLike(String value) {
            addCriterion("TRADE_START_TIME not like", value, "tradeStartTime");
            return (Criteria) this;
        }

        public Criteria andTradeStartTimeIn(List<String> values) {
            addCriterion("TRADE_START_TIME in", values, "tradeStartTime");
            return (Criteria) this;
        }

        public Criteria andTradeStartTimeNotIn(List<String> values) {
            addCriterion("TRADE_START_TIME not in", values, "tradeStartTime");
            return (Criteria) this;
        }

        public Criteria andTradeStartTimeBetween(String value1, String value2) {
            addCriterion("TRADE_START_TIME between", value1, value2, "tradeStartTime");
            return (Criteria) this;
        }

        public Criteria andTradeStartTimeNotBetween(String value1, String value2) {
            addCriterion("TRADE_START_TIME not between", value1, value2, "tradeStartTime");
            return (Criteria) this;
        }

        public Criteria andTradeEndTimeIsNull() {
            addCriterion("TRADE_END_TIME is null");
            return (Criteria) this;
        }

        public Criteria andTradeEndTimeIsNotNull() {
            addCriterion("TRADE_END_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andTradeEndTimeEqualTo(String value) {
            addCriterion("TRADE_END_TIME =", value, "tradeEndTime");
            return (Criteria) this;
        }

        public Criteria andTradeEndTimeNotEqualTo(String value) {
            addCriterion("TRADE_END_TIME <>", value, "tradeEndTime");
            return (Criteria) this;
        }

        public Criteria andTradeEndTimeGreaterThan(String value) {
            addCriterion("TRADE_END_TIME >", value, "tradeEndTime");
            return (Criteria) this;
        }

        public Criteria andTradeEndTimeGreaterThanOrEqualTo(String value) {
            addCriterion("TRADE_END_TIME >=", value, "tradeEndTime");
            return (Criteria) this;
        }

        public Criteria andTradeEndTimeLessThan(String value) {
            addCriterion("TRADE_END_TIME <", value, "tradeEndTime");
            return (Criteria) this;
        }

        public Criteria andTradeEndTimeLessThanOrEqualTo(String value) {
            addCriterion("TRADE_END_TIME <=", value, "tradeEndTime");
            return (Criteria) this;
        }

        public Criteria andTradeEndTimeLike(String value) {
            addCriterion("TRADE_END_TIME like", value, "tradeEndTime");
            return (Criteria) this;
        }

        public Criteria andTradeEndTimeNotLike(String value) {
            addCriterion("TRADE_END_TIME not like", value, "tradeEndTime");
            return (Criteria) this;
        }

        public Criteria andTradeEndTimeIn(List<String> values) {
            addCriterion("TRADE_END_TIME in", values, "tradeEndTime");
            return (Criteria) this;
        }

        public Criteria andTradeEndTimeNotIn(List<String> values) {
            addCriterion("TRADE_END_TIME not in", values, "tradeEndTime");
            return (Criteria) this;
        }

        public Criteria andTradeEndTimeBetween(String value1, String value2) {
            addCriterion("TRADE_END_TIME between", value1, value2, "tradeEndTime");
            return (Criteria) this;
        }

        public Criteria andTradeEndTimeNotBetween(String value1, String value2) {
            addCriterion("TRADE_END_TIME not between", value1, value2, "tradeEndTime");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNull() {
            addCriterion("PRIORITY is null");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNotNull() {
            addCriterion("PRIORITY is not null");
            return (Criteria) this;
        }

        public Criteria andPriorityEqualTo(Integer value) {
            addCriterion("PRIORITY =", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotEqualTo(Integer value) {
            addCriterion("PRIORITY <>", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThan(Integer value) {
            addCriterion("PRIORITY >", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThanOrEqualTo(Integer value) {
            addCriterion("PRIORITY >=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThan(Integer value) {
            addCriterion("PRIORITY <", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThanOrEqualTo(Integer value) {
            addCriterion("PRIORITY <=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityIn(List<Integer> values) {
            addCriterion("PRIORITY in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotIn(List<Integer> values) {
            addCriterion("PRIORITY not in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityBetween(Integer value1, Integer value2) {
            addCriterion("PRIORITY between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotBetween(Integer value1, Integer value2) {
            addCriterion("PRIORITY not between", value1, value2, "priority");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_route_channel
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 02 16:08:16 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_route_channel
     *
     * @mbggenerated Tue Jun 02 16:08:16 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}