package com.customized.libs.shardingsphere.entity.generate;

import java.io.Serializable;

public class TSpringScheduledCron implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spring_scheduled_cron.cron_id
     *
     * @mbggenerated Wed Oct 21 09:22:23 CST 2020
     */
    private Integer cronId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spring_scheduled_cron.cron_key
     *
     * @mbggenerated Wed Oct 21 09:22:23 CST 2020
     */
    private String cronKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spring_scheduled_cron.cron_expression
     *
     * @mbggenerated Wed Oct 21 09:22:23 CST 2020
     */
    private String cronExpression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spring_scheduled_cron.task_explain
     *
     * @mbggenerated Wed Oct 21 09:22:23 CST 2020
     */
    private String taskExplain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spring_scheduled_cron.status
     *
     * @mbggenerated Wed Oct 21 09:22:23 CST 2020
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_spring_scheduled_cron
     *
     * @mbggenerated Wed Oct 21 09:22:23 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spring_scheduled_cron.cron_id
     *
     * @return the value of t_spring_scheduled_cron.cron_id
     * @mbggenerated Wed Oct 21 09:22:23 CST 2020
     */
    public Integer getCronId() {
        return cronId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spring_scheduled_cron.cron_id
     *
     * @param cronId the value for t_spring_scheduled_cron.cron_id
     * @mbggenerated Wed Oct 21 09:22:23 CST 2020
     */
    public void setCronId(Integer cronId) {
        this.cronId = cronId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spring_scheduled_cron.cron_key
     *
     * @return the value of t_spring_scheduled_cron.cron_key
     * @mbggenerated Wed Oct 21 09:22:23 CST 2020
     */
    public String getCronKey() {
        return cronKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spring_scheduled_cron.cron_key
     *
     * @param cronKey the value for t_spring_scheduled_cron.cron_key
     * @mbggenerated Wed Oct 21 09:22:23 CST 2020
     */
    public void setCronKey(String cronKey) {
        this.cronKey = cronKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spring_scheduled_cron.cron_expression
     *
     * @return the value of t_spring_scheduled_cron.cron_expression
     * @mbggenerated Wed Oct 21 09:22:23 CST 2020
     */
    public String getCronExpression() {
        return cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spring_scheduled_cron.cron_expression
     *
     * @param cronExpression the value for t_spring_scheduled_cron.cron_expression
     * @mbggenerated Wed Oct 21 09:22:23 CST 2020
     */
    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spring_scheduled_cron.task_explain
     *
     * @return the value of t_spring_scheduled_cron.task_explain
     * @mbggenerated Wed Oct 21 09:22:23 CST 2020
     */
    public String getTaskExplain() {
        return taskExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spring_scheduled_cron.task_explain
     *
     * @param taskExplain the value for t_spring_scheduled_cron.task_explain
     * @mbggenerated Wed Oct 21 09:22:23 CST 2020
     */
    public void setTaskExplain(String taskExplain) {
        this.taskExplain = taskExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spring_scheduled_cron.status
     *
     * @return the value of t_spring_scheduled_cron.status
     * @mbggenerated Wed Oct 21 09:22:23 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spring_scheduled_cron.status
     *
     * @param status the value for t_spring_scheduled_cron.status
     * @mbggenerated Wed Oct 21 09:22:23 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}